[project]
name = "asana-integrator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "devktelesz", email = "kacpertelesz@europ.com.pl" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
asana-integrator = "asana_integrator:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
